Run tools/generate_dnsplugins_postrefreshhook.sh

diff --git a/certbot-dns-route53/snap/hooks/post-refresh b/certbot-dns-route53/snap/hooks/post-refresh
--- a/certbot-dns-route53/snap/hooks/post-refresh
+++ b/certbot-dns-route53/snap/hooks/post-refresh
@@ -13,8 +13,9 @@ cb_installed=$(cat $SNAP/certbot-shared/certbot-version.txt)
 cb_required=$(grep -oP "version = '\K.*(?=')" $SNAP/setup.py)
 
 
-/bin/python3 -c "import sys; from setuptools._vendor.packaging import version; sys.exit(1) if  version.parse('$cb_installed') < version.parse('$cb_required') else sys.exit(0)" || exit_code=$?
+$SNAP/bin/python3 -c "import sys; from packaging import version; sys.exit(1) if  version.parse('$cb_installed') < version.parse('$cb_required') else sys.exit(0)" || exit_code=$?
 if [ "$exit_code" -eq 1 ]; then
-  echo "Certbot is version $cb_installed but needs to be at least $cb_required before"     "this plugin can be updated; will try again on next refresh."
+  echo "Certbot is version $cb_installed but needs to be at least $cb_required before" \
+    "this plugin can be updated; will try again on next refresh."
   exit 1
 fi
