Properly handle noop bootstrap functions.

diff --git a/letsencrypt-auto-source/letsencrypt-auto.template b/letsencrypt-auto-source/letsencrypt-auto.template
--- a/letsencrypt-auto-source/letsencrypt-auto.template
+++ b/letsencrypt-auto-source/letsencrypt-auto.template
@@ -251,12 +251,13 @@ DeterminePythonVersion() {
 
 # Set Bootstrap to the function that installs OS dependencies on this system
 # and BOOTSTRAP_VERSION to the unique identifier for the current version of
-# that function.
+# that function. If Bootstrap is set to a function that doesn't install any
+# packages (either because --no-bootstrap was included on the command line or
+# we don't know how to bootstrap on this system), BOOTSTRAP_VERSION is not set.
 if [ "$NO_BOOTSTRAP" = 1 ]; then
   Bootstrap() {
     :
   }
-  BOOTSTRAP_VERSION="NO_BOOTSTRAP 1"
 elif [ -f /etc/debian_version ]; then
   Bootstrap() {
     BootstrapMessage "Debian-based OSes"
@@ -335,18 +336,19 @@ else
     error "for more info."
     exit 1
   }
-  BOOTSTRAP_VERSION="Unknown 1"
 fi
 
-PrevBootstrapVersion() {
+# Sets PREV_BOOTSTRAP_VERSION to the identifier for the bootstrap script used
+# to install OS dependencies on this system. PREV_BOOTSTRAP_VERSION isn't set
+# if it is unknown how OS dependencies were installed on this system.
+SetPrevBootstrapVersion() {
   if [ -f $BOOTSTRAP_VERSION_PATH ]; then
-    cat "$BOOTSTRAP_VERSION_PATH"
+    PREV_BOOTSTRAP_VERSION=$(cat "$BOOTSTRAP_VERSION_PATH")
   # The list below only contains bootstrap version strings that existed before
   # we started writing them to disk.
   #
   # DO NOT MODIFY THIS LIST UNLESS YOU KNOW WHAT YOU'RE DOING!
   elif grep -Fqx "$BOOTSTRAP_VERSION" << "UNLIKELY_EOF"
-NO_BOOTSTRAP 1
 BootstrapDebCommon 1
 BootstrapMageiaCommon 1
 BootstrapRpmCommon 1
@@ -362,9 +364,7 @@ UNLIKELY_EOF
     # bootstrap script is from before we started saving the version number,
     # return the currently selected version to prevent us from rebootstrapping
     # unnecessarily.
-    echo "$BOOTSTRAP_VERSION"
-  else
-    echo "Unknown 0"
+    PREV_BOOTSTRAP_VERSION="$BOOTSTRAP_VERSION"
   fi
 }
 
@@ -378,34 +378,39 @@ if [ "$1" = "--le-auto-phase2" ]; then
   # Phase 2: Create venv, install LE, and run.
 
   shift 1  # the --le-auto-phase2 arg
-  # If the venv doesn't exist, we just bootstrapped
-  if [ -d "$VENV_PATH" -a "$BOOTSTRAP_VERSION" != "$(PrevBootstrapVersion)" ]; then
-    # if non-interactive mode or stdin and stdout are connected to a terminal
-    if [ \( "$NONINTERACTIVE" = 1 \) -o \( \( -t 0 \) -a \( -t 1 \) \) ]; then
-      rm -rf "$VENV_PATH"
-      "$0" "$@"
-      exit 0
-    else
-      error "Skipping upgrade because new OS dependencies may need to be installed."
-      error
-      error "To upgrade to a newer version, please run this script again manually so you can"
-      error "approve changes or with --non-interactive on the command line to automatically"
-      error "install any required packages."
-      # Set INSTALLED_VERSION to be the same so we don't update the venv
-      INSTALLED_VERSION="$LE_AUTO_VERSION"
+  SetPrevBootstrapVersion
+
+  INSTALLED_VERSION="none"
+  if [ -d "$VENV_PATH" ]; then
+    # If the selected Bootstrap function isn't a noop and it differs from the
+    # previously used version
+    if [ -n "$BOOTSTRAP_VERSION" -a "$BOOTSTRAP_VERSION" != "$PREV_BOOTSTRAP_VERSION" ]; then
+      # if non-interactive mode or stdin and stdout are connected to a terminal
+      if [ \( "$NONINTERACTIVE" = 1 \) -o \( \( -t 0 \) -a \( -t 1 \) \) ]; then
+        rm -rf "$VENV_PATH"
+        "$0" "$@"
+        exit 0
+      else
+        error "Skipping upgrade because new OS dependencies may need to be installed."
+        error
+        error "To upgrade to a newer version, please run this script again manually so you can"
+        error "approve changes or with --non-interactive on the command line to automatically"
+        error "install any required packages."
+        # Set INSTALLED_VERSION to be the same so we don't update the venv
+        INSTALLED_VERSION="$LE_AUTO_VERSION"
+      fi
+    elif [ -f "$VENV_BIN/letsencrypt" ]; then
+      # --version output ran through grep due to python-cryptography DeprecationWarnings
+      # grep for both certbot and letsencrypt until certbot and shim packages have been released
+      INSTALLED_VERSION=$("$VENV_BIN/letsencrypt" --version 2>&1 | grep "^certbot\|^letsencrypt" | cut -d " " -f 2)
+      if [ -z "$INSTALLED_VERSION" ]; then
+          error "Error: couldn't get currently installed version for $VENV_BIN/letsencrypt: " 1>&2
+          "$VENV_BIN/letsencrypt" --version
+          exit 1
+      fi
     fi
-  elif [ -f "$VENV_BIN/letsencrypt" ]; then
-    # --version output ran through grep due to python-cryptography DeprecationWarnings
-    # grep for both certbot and letsencrypt until certbot and shim packages have been released
-    INSTALLED_VERSION=$("$VENV_BIN/letsencrypt" --version 2>&1 | grep "^certbot\|^letsencrypt" | cut -d " " -f 2)
-    if [ -z "$INSTALLED_VERSION" ]; then
-        error "Error: couldn't get currently installed version for $VENV_BIN/letsencrypt: " 1>&2
-        "$VENV_BIN/letsencrypt" --version
-        exit 1
-    fi
-  else
-    INSTALLED_VERSION="none"
   fi
+
   if [ "$LE_AUTO_VERSION" != "$INSTALLED_VERSION" ]; then
     say "Creating virtual environment..."
     DeterminePythonVersion
@@ -415,7 +420,12 @@ if [ "$1" = "--le-auto-phase2" ]; then
     else
       virtualenv --no-site-packages --python "$LE_PYTHON" "$VENV_PATH" > /dev/null
     fi
-    echo "$BOOTSTRAP_VERSION" > "$BOOTSTRAP_VERSION_PATH"
+
+    if [ -n "$BOOTSTRAP_VERSION" ]; then
+      echo "$BOOTSTRAP_VERSION" > "$BOOTSTRAP_VERSION_PATH"
+    elif [ -n "$PREV_BOOTSTRAP_VERSION" ]; then
+      echo "$PREV_BOOTSTRAP_VERSION" > "$BOOTSTRAP_VERSION_PATH"
+    fi
 
     say "Installing Python packages..."
     TEMP_DIR=$(TempDir)
