only necessary items

diff --git a/.github/workflows/packaging_jobs.yml b/.github/workflows/packaging_jobs.yml
--- a/.github/workflows/packaging_jobs.yml
+++ b/.github/workflows/packaging_jobs.yml
@@ -80,32 +80,32 @@ jobs:
   #   - name: Run integration tests for Docker images
   #     run: set -e && tools/docker/test.sh ${{ env.dockerTag }} ${{ matrix.DOCKER_ARCH }}
   #     shell: bash
-  gha_build:
-    name: Build ${{ matrix.build-for }} certbot snap
-    runs-on: ${{ matrix.build-on }}
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-        - build-for: arm64
-          build-on: ubuntu-24.04-arm
-        - build-for: amd64
-          build-on: ubuntu-24.04
-    steps:
-      - uses: actions/checkout@v6.0.2
-      - uses: snapcore/action-build@v1.3.0
-        id: build
-        with:
-          snapcraft-args: "--build-for=${{ matrix.build-for }}"
-      - name: Prepare artifact
-        run: |-
-          set -e
-          mv *.snap ${{ runner.temp }}
-      - name: Store snap artifact
-        uses: actions/upload-artifact@v7.0.0
-        with:
-          name: snaps_${{ matrix.build-for }}
-          path: "${{ runner.temp }}"
+  # gha_build:
+  #   name: Build ${{ matrix.build-for }} certbot snap
+  #   runs-on: ${{ matrix.build-on }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #       - build-for: arm64
+  #         build-on: ubuntu-24.04-arm
+  #       - build-for: amd64
+  #         build-on: ubuntu-24.04
+  #   steps:
+  #     - uses: actions/checkout@v6.0.2
+  #     - uses: snapcore/action-build@v1.3.0
+  #       id: build
+  #       with:
+  #         snapcraft-args: "--build-for=${{ matrix.build-for }}"
+  #     - name: Prepare artifact
+  #       run: |-
+  #         set -e
+  #         mv *.snap ${{ runner.temp }}
+  #     - name: Store snap artifact
+  #       uses: actions/upload-artifact@v7.0.0
+  #       with:
+  #         name: snaps_${{ matrix.build-for }}
+  #         path: "${{ runner.temp }}"
   generate_dns_list_matrix:
     runs-on: ubuntu-latest
     outputs:
@@ -150,77 +150,77 @@ jobs:
         with:
           name: snaps_${{ matrix.build-for }}
           path: "${{ runner.temp }}"
-  launchpad_build:
-    name: Build armhf snaps
-    runs-on:
-      - ubuntu-24.04
-    strategy:
-      matrix:
-        SNAP_ARCH:
-        - armhf
-    steps:
-    - name: checkout
-      uses: actions/checkout@v6.0.2
-    - name: Install dependencies
-      run: |-
-        set -e
-        sudo apt-get update
-        sudo apt-get install -y --no-install-recommends snapd
-        sudo snap install --classic snapcraft
-    - uses: actions/setup-python@v5.0.0
-      with:
-        python-version: '3.12'
-    - name: Build snaps
-      env:
-        SNAPCRAFT_STORE_CREDENTIALS: "${{ secrets.LAUNCHPAD_CREDENTIALS }}"
-      run: |-
-        set -e
-        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
-        git config --global user.name "${{ github.actor }}"
-        python3 tools/snap/build_remote.py ALL --archs ${{ matrix.SNAP_ARCH }} --timeout ${{ env.snapBuildTimeout }}
-    - name: Prepare artifacts
-      run: |-
-        set -e
-        mv *.snap ${{ runner.temp }}
-        mv certbot-dns-*/*.snap ${{ runner.temp }}
-    - name: Store snaps artifacts
-      uses: actions/upload-artifact@v4.1.0
-      with:
-        name: snaps_${{ matrix.SNAP_ARCH }}
-        path: "${{ runner.temp }}"
-  snap_run:
-    needs:
-    - gha_build
-    runs-on:
-      - ubuntu-24.04
-    steps:
-    - name: checkout
-      uses: actions/checkout@v6.0.2
-    - uses: actions/setup-python@v5.0.0
-      with:
-        python-version: '3.12'
-    - name: Install dependencies
-      run: |-
-        set -e
-        sudo apt-get update
-        sudo apt-get install -y --no-install-recommends nginx-light snapd
-        python3 -m venv venv
-        venv/bin/python tools/pip_install.py -U tox
-    - name: Retrieve Certbot snaps
-      uses: actions/download-artifact@v8.0.1
-      with:
-        name: snaps_amd64
-        github_token: "${{ secrets.GITHUB_TOKEN }}"
-        path: "${{ github.workspace }}/snap"
-        repo: "${{ github.repository }}"
-    - name: Install Certbot snap
-      run: |-
-        set -e
-        sudo snap install --dangerous --classic snap/certbot_*.snap
-    - name: Run tox
-      run: |-
-        set -e
-        venv/bin/python -m tox run -e integration-external,apacheconftest-external-with-pebble
+  # launchpad_build:
+  #   name: Build armhf snaps
+  #   runs-on:
+  #     - ubuntu-24.04
+  #   strategy:
+  #     matrix:
+  #       SNAP_ARCH:
+  #       - armhf
+  #   steps:
+  #   - name: checkout
+  #     uses: actions/checkout@v6.0.2
+  #   - name: Install dependencies
+  #     run: |-
+  #       set -e
+  #       sudo apt-get update
+  #       sudo apt-get install -y --no-install-recommends snapd
+  #       sudo snap install --classic snapcraft
+  #   - uses: actions/setup-python@v5.0.0
+  #     with:
+  #       python-version: '3.12'
+  #   - name: Build snaps
+  #     env:
+  #       SNAPCRAFT_STORE_CREDENTIALS: "${{ secrets.LAUNCHPAD_CREDENTIALS }}"
+  #     run: |-
+  #       set -e
+  #       git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
+  #       git config --global user.name "${{ github.actor }}"
+  #       python3 tools/snap/build_remote.py ALL --archs ${{ matrix.SNAP_ARCH }} --timeout ${{ env.snapBuildTimeout }}
+  #   - name: Prepare artifacts
+  #     run: |-
+  #       set -e
+  #       mv *.snap ${{ runner.temp }}
+  #       mv certbot-dns-*/*.snap ${{ runner.temp }}
+  #   - name: Store snaps artifacts
+  #     uses: actions/upload-artifact@v4.1.0
+  #     with:
+  #       name: snaps_${{ matrix.SNAP_ARCH }}
+  #       path: "${{ runner.temp }}"
+  # snap_run:
+  #   needs:
+  #   - gha_build
+  #   runs-on:
+  #     - ubuntu-24.04
+  #   steps:
+  #   - name: checkout
+  #     uses: actions/checkout@v6.0.2
+  #   - uses: actions/setup-python@v5.0.0
+  #     with:
+  #       python-version: '3.12'
+  #   - name: Install dependencies
+  #     run: |-
+  #       set -e
+  #       sudo apt-get update
+  #       sudo apt-get install -y --no-install-recommends nginx-light snapd
+  #       python3 -m venv venv
+  #       venv/bin/python tools/pip_install.py -U tox
+  #   - name: Retrieve Certbot snaps
+  #     uses: actions/download-artifact@v8.0.1
+  #     with:
+  #       name: snaps_amd64
+  #       github_token: "${{ secrets.GITHUB_TOKEN }}"
+  #       path: "${{ github.workspace }}/snap"
+  #       repo: "${{ github.repository }}"
+  #   - name: Install Certbot snap
+  #     run: |-
+  #       set -e
+  #       sudo snap install --dangerous --classic snap/certbot_*.snap
+  #   - name: Run tox
+  #     run: |-
+  #       set -e
+  #       venv/bin/python -m tox run -e integration-external,apacheconftest-external-with-pebble
   snap_dns_run:
     needs:
     - gha_build_dns
